### PR TITLE
Fix block types

### PR DESCRIPTION
**Pull request by kristiank**
Here's some simple fixes first, but I can add more types based on the discussion in #25.

### CODE REVIEW

**Comment by kristiank** [comment]
I can't find any troubles with these commits and I think we can continue the discussion on types before I proceed with further changes.

**Comment by RichoM** [comment]
If you agree, I will merge this pull request and make a new release. I think the improvements we've been adding in the last couple of months deserve their own release. And then we can proceed with the bigger changes.

**Comment by kristiank** [comment]
Yes, I agree!

**Comment by kristiank** [comment]
For the next release I'd like to define the blocks mentioned in #28 using `initBlock` and translation messages. This way we'd have a complete translation base for the next release. I could also make an effort to rewrite all translation messages so they use %labels instead of %1-numbers. What do you think?

**Pull request merged**
